#!/usr/bin/env bash
set -euo pipefail

root_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
fonts_dir="$root_dir/docs/public/fonts"
css_out="$root_dir/docs/.vitepress/theme/fonts.css"

a_ua='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36'
roboto_url='https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap'
quicksand_url='https://fonts.googleapis.com/css2?family=Quicksand:wght@400;700&display=swap'

mkdir -p "$fonts_dir"

tmp_dir=$(mktemp -d)
cleanup() { rm -rf "$tmp_dir"; }
trap cleanup EXIT

curl -sSL -A "$a_ua" "$roboto_url" -o "$tmp_dir/roboto.css"
curl -sSL -A "$a_ua" "$quicksand_url" -o "$tmp_dir/quicksand.css"

css_combined=$(cat "$tmp_dir/roboto.css" "$tmp_dir/quicksand.css")

mapfile -t urls < <(rg -o "https://fonts.gstatic.com/s/[^)]+\\.woff2" -N "$tmp_dir/roboto.css" "$tmp_dir/quicksand.css" | sort -u)

for url in "${urls[@]}"; do
  file_name=$(basename "$url")
  curl -sSL -A "$a_ua" "$url" -o "$fonts_dir/$file_name"
  css_combined=$(printf '%s' "$css_combined" | perl -pe "s#\\Q$url\\E#/fonts/$file_name#g")
done

{
  echo "/* Generated by scripts/download-fonts.sh; do not edit by hand. */"
  echo
  printf '%s\n' "$css_combined"
} > "$css_out"

echo "Saved fonts to $fonts_dir"
echo "Wrote CSS to $css_out"
